### ISSUE TITLE
Video demonstratrion

### ISSUE THREAD

**Issue by erichideki** [motet/baldr#2]
Hello!

Can you make a little video showing how this project works? For exemple, how works the simulator. Nothing special, just 2 minutes :)

**Comment by lindemer** [comment]
Since you asked nicely :)
https://www.youtube.com/watch?v=0st4ma6SF8Y&feature=youtu.be

**Comment by erichideki** [comment]
Nice! I will share with my friends now :)

**Comment by lindemer** [comment]
Great, thanks!
